config/routes.rb
Rails.application.routes.draw do



devise_for :users, :controllers => {:sessions => "sessions"},
path: '/',
:path_names => {
    :sign_in  => 'login',
    :sign_up  => 'sign_up',
    :sign_out => 'logout'
  }


  root 'pages#home'
  resources :actualities, only: [:index, :show]
  resources :tips, only: [:index, :show]
  resources :password_resets
    
  namespace :admin_v2 do
    resources :actualities, except: [:show]
    resources :users, except: [:show]
    resources :projects, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tips, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tipcategories, only: [:new ,:create ,:edit, :destroy ,:index]
    resources :alerts, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :interview, only: [:new ,:create ,:index]
    resources :applicants, only: [:index,:show]
    resources :admin, only: [:index,:new]
    resources :companies, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :jobs, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :admin, only: [:index]
 end

  resource :applicant, only: [:new, :create, :edit, :update, :show]
  resource :user, only: [:edit,:update]


  post 'admin_v2/applicants/index/user_vote' => 'admin#user_vote', :as => 'user_vote'
  post 'admin_v2/applicants/index/user_vote_cancel' => 'admin#user_vote_cancel', :as => 'user_vote_cancel'

  post 'admin/show_applicants/applicant_complete', :to => 'admin#applicant_complete', :as => 'applicant_complete'
  post 'admin/show_applicants/ok_for_interview', :to => 'admin#ok_for_interview', :as => 'ok_for_interview'
  post 'admin/show_applicants/is_refused', :to => 'admin#is_refused', :as => 'is_refused'
  post 'admin/show_applicants/is_accepted', :to => 'admin#is_accepted', :as => 'is_accepted'
  post 'admin/show_applicants/applicant_finish', :to => 'admin#applicant_finish', :as => 'applicant_finish'
  post 'admin/show_applicants/interview_result', :to => 'admin#interview_result', :as => 'interview_result'
  post 'admin/show_applicants/user_destroy', :to => 'admin#user_destroy', :as => 'user_destroy'
  get 'admin_v2/enable/:id' => 'admin_v2/jobs#enable', :as => 'admin_v2_enable_job'
  get 'admin_v2/disable/:id' => 'admin_v2/jobs#disable', :as => 'admin_v2_disable_job'

  get 'admin' => 'admin#index'
  get 'admin/sign_up' => 'admin#index'
  get 'admin/student_old/:id/graduate_student' => 'admin#graduate_student', :as => 'admin_graduate_student'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/show_applicants/send_remind', :to => 'admin#send_remind', :as => 'send_remind'



  get 'admin/show_options' => 'admin#show_options'
  get 'admin/show_options' => 'admin#show_options'
  post 'admin/update_options' => 'admin#update_options'

  get '/annuaire' => 'companies#annuary', :as => 'annuary'
  get '/entreprises/:page' => 'companies#companies', :as => "companies", defaults: { page: 1 }
  get '/entreprise/:id' => 'companies#company', :as => "company"
  get '/offres/:page' => 'jobs#jobs', :as => 'jobs', defaults: {page: 1}
  get '/offre/:id' => 'jobs#job', :as => 'job'

  get '/', :to => 'pages#home'
  get '/formation', :to => 'pages#formation'
  get '/projets', :to => 'pages#project'
  get '/equipe', :to => 'pages#team'
  get '/ucp', :to => 'pages#ucp'
  get '/informations', :to => 'pages#map'
  post '/informations/sendmail', :to => 'pages#sendmail'
  get '/postuler', :to => 'applicants#new'
  post '/postuler/login', :to => 'applicant#applicant_login', :as => 'applicant_login'
  get '/postuler/:assurance', :to => 'applicant#applicant_create_apply', :as => 'applicant_create_apply'
  post '/postuler/new', :to => 'applicant#create_apply', :as => 'create_apply'
  patch '/postuler/:assurance', :to => 'applicant#update_apply', :as => 'update_apply'
  get '/mentions', :to => 'pages#mentions'
  get '/live', :to => 'pages#live'

  get '/studentsbook', :to => 'student#show', :as => 'students_list'
  get '/studentsbook/:graduation_years' , :to => 'student#show', :as => 'students_list_by_year'
  post 'studentsbook/', :to => 'student#show'
  post 'studentsbook/:graduation_years', :to => 'student#show'
  get '/studentprofil/:user_id', :to => 'student#profil', :as => 'student_profil'
  post '/studentprofil/sendmail', :to => 'student#sendmail'
  get '/studentprofil/edit/:user_id', :to => 'student#edit', :as => 'student_profil_edit'
  post '/studentprofil/update_user/:user_id', :to => 'student#update_user'
  resources :tips, only: [:show,:index] do
    resources :errors_tips
  end
end

app/views/admin/create_actuality.html.erb
<h2>Ajouter une actualité</h2>
<%= form_for(@actuality, url:  admin_create_actuality_path, html: {class: "form" }) do |f| %>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :title, autofocus: true , :class => 'input' ,:placeholder=>"Titre" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
 
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.hidden_field :author , :value => current_user.email %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.submit "Creer actualité", :class => 'input-btn' %>
  </div>
</div>
<% end %>

app/views/admin/create_user.html.erb
<h2>Créer un compte d'utilisateur</h2>
<%= form_for(:user, html: {class: "form" }) do |f| %>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.email_field :email, autofocus: true , :class => 'input' ,:placeholder=>"Email" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :name, autofocus: true , :class => 'input' ,:placeholder=>"Prénom" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :lastname, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
  </div>
</div>
<div class="form-group">
  <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %>
  <div class="col-sm-10">
    <%= f.password_field :password, autocomplete: "off", :class => 'input' ,:placeholder=>"Mot de passe" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.password_field :password_confirmation, autocomplete: "off" , :class => 'input' ,:placeholder=>"Confirmer le mot de passe" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.collection_select :role, User::ROLES, :to_s, :humanize  %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.submit "Creer utilisateur", :class => 'input-btn' %>
  </div>
</div>
<% end %>

app/views/admin/edit_actuality.html.erb
<h2>Modifier actualité</h2>
<%= current_user.email %>
<%= form_for(:thisActuality, url:  admin_edit_actuality_path, html: {class: "form" }) do |f| %>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :title, autofocus: true , :class => 'input' ,:placeholder=>"Titre" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_area :content, :class => "tinymce", :rows => 40, :cols => 120 %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.hidden_field :author, :value => current_user.email %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.submit "Mise à jour", :class => 'input-btn' %>
  </div>
</div>
<% end %>

app/views/admin/edit_user.html.erb
<h2>Modifier l'utilisateur</h2>

<%= form_for(:user, html: {class: "form" }) do |f| %>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.email_field :email, autofocus: true , :class => 'input' ,:placeholder=>"Email" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :name, autofocus: true , :class => 'input' ,:placeholder=>"Prénom" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :lastname, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
  </div>
</div>
<div class="form-group">
  <% if @validatable %><i>(<%= @minimum_password_length %> characters minimum)</i><% end %>
  <div class="col-sm-10">
    <%= f.password_field :password, autocomplete: "off", :class => 'input' ,:placeholder=>"Mot de passe" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.password_field :password_confirmation, autocomplete: "off" , :class => 'input' ,:placeholder=>"Confirmer mot de passe" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :description, :class => 'input' ,:placeholder=>"Poste de l'utilisateur" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :twitter, :class => 'input' ,:placeholder=>"Lien Twitter" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :linkin, :class => 'input' ,:placeholder=>"Lien Linkedin" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.text_field :photo, :class => 'input' ,:placeholder=>"Lien vers votre photo" %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.collection_select :role, User::ROLES, :to_s, :humanize  %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-10">
    <%= f.submit "Mise à jour", :class => 'input-btn' %>
  </div>
</div>
<% end %>

app/views/admin/index.html.erb
<h1>Bonjour <%= current_user.name %>, voici un résumé des stats du site actuel :</h1>
</br>
<table class="table">
    <tbody>
        <tr>
            <td data-th="Utilisateurs" >Utilisateurs</td>
            <td data-th="Nombre d'utilisateurs" ><%= @users.count %></td>
        </tr>
        <tr>
       		<td data-th="Projets" >Projets</td>
            <td data-th="Nombre de projets" ><%= @projects.count %></td>
        </tr>
        <tr>
       		<td data-th="Alertes" >Alertes</td>
            <td data-th="Nombre d'alertes" ><%= @alerts.count %></td>
        </tr>
        <tr>
            <td data-th="Candidatures" >Candidatures entrées</td>
            <td data-th="Nombre de candidatures" ><%= @applicants.count %></td>
        </tr>
    </tbody>
</table>
<br />

<!-- Les 5 derniers dossiers -->

<h1>Dernières candidatures</h1>
<table class="table applicants myTable" >
    <thead>
    <tr>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Date de dépot</th>
        <th>Avis</th>
        <th>Votre avis</th>
        <th>Options</th>
        <th class="important-section-list">Status</th>
    </tr>
    </thead>
    <tbody>
    <% @count = 0
    @lasts.each do |last| %>
    <tr>
        <td data-th="Nom" ><%= last.name %></td>
        <td data-th="Prénom" ><%= last.first_name %></td>
        <td data-th="Date_depot" >
        <%= last.updated_at.to_time.strftime("%d/%m/%Y") %></td>
        <td data-th="Vote" >
            <%
            @positif = 0
            @neutre = 0
            @negatif = 0
            @your_vote = -1

            last.votes.each do |vote|
            if vote.id_voter == @user.id
                @your_vote = vote.value
            end
            if vote.value == 2
            @positif += 1
            elsif vote.value == 1
            @negatif += 1
            else
            @neutre += 1
            end
            end
            %>
            <span class="badge badge-green">+<%= @positif %></span>
            <span class="badge badge-yellow">=<%= @neutre %></span>
            <span class="badge badge-red">-<%= @negatif %></span>
        </td>
        <td>
            <%  if @your_vote == -1 %>
            Pas encore voté
            <%  elsif @your_vote == 0 %>
            <span class="badge badge-yellow">Neutre</span>
            <%  elsif @your_vote == 1 %>
            <span class="badge badge-red">Négatif</span>
            <%  elsif @your_vote == 2 %>
            <span class="badge badge-green">Positif</span>
            <%  end %>
        </td>
        <td data-th="Voir">
            <%= link_to(admin_v2_applicant_path(last), :class=>'badge badge-blue') do %>
            <i class="fa fa-eye"></i> voir
            <% end %>

        </td>
        <td class="important-section-list" data-th="Status">
            <% if last.applicant_status != nil %>
            <% @status = last.applicant_status %>
            <%= status_applicant(@status) %>
            <% else %>
            <span class="alert alert-error">Erreur dans la base de donnée : le dossier n'a pas de status lié</span>
            <% end %>
        </td>
    </tr>
    <% @count += 1
        if @count == 5
            break;
        end
    end %>
    </tbody>
</table>
<%= link_to admin_v2_applicants_path(), :class=>'button button-blue' do %>Voir toutes les candidatures<% end %>

<!-- Candidatures acceptées -->
<br />
<%
@count_accepted = 0
@applicants.each do |applicant|
        if applicant.applicant_status != nil
        @status = applicant.applicant_status
        if @status.applicant_response == 1
            @count_accepted += 1;
        end
    end
end
%>
<h1>Candidatures acceptées (<%= @count_accepted %>)</h1>
<table class="table applicants myTable">
    <thead>
    <tr>
        <th>ID</th>
        <th>Prénom</th>
        <th>Nom</th>
        <th>Date de dépot</th>
        <th>Options</th>

    </tr>
    </thead>
    <tbody>
    <% @applicants.each do |applicant|
        if applicant.applicant_status != nil
            @status = applicant.applicant_status
                if @status.applicant_response == 1%>
                <tr>
                    <td data-th="ID" ><%= applicant.id %></td>
                    <td data-th="Nom" ><%= applicant.name %></td>
                    <td data-th="Prénom" ><%= applicant.first_name %></td>
                    <td data-th="Date_depot" ><%= applicant.updated_at.to_time.strftime("%d/%m/%Y") %></td>
                    <td data-th="Voir">
                        <%= link_to(admin_v2_applicant_path(applicant), :class=>'badge badge-blue') do %>
                        <i class="fa fa-eye"></i> voir
                        <% end %>
                    </td>
                </tr>
            <% end
        end
    end %>
    </tbody>
</table>

app/views/admin/new_actuality.html.erb
<%    	if @actuality.save %>
    <%= @actuality.inspect %>
    <%=		flash["sucess"] ="Succès" %>
    <%	else %>
    <%=		flash["deny"] ="Erreur" %>
    <%= @actuality.inspect %>
    <%	end %>

app/views/admin/show_actualities.html.erb
<h1>Gérer les comptes actualité</h1>
<%= link_to(admin_create_actuality_path(),:class=>'button button-blue float-right') do %>
    <span>Créer Actualité</span> <i class="fa fa-newspaper-o"></i>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Titre</th>
            <th>Auteur</th>
            <th>Date de création</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @actualities.each do |actuality| %>
        <tr>
            <td data-th="ID" ><%= actuality.id %></td>
            <td data-th="Titre" ><%= actuality.title %></td>
            <td data-th="Auteur" ><%= actuality.author %></td>
            <td data-th="Créé le" ><%= actuality.created_at.to_time.strftime("%m/%d/%Y") %></td>
            <td data-th="Action" >
                <%= link_to(admin_edit_actuality_path(actuality)) do %>
                <i class="fa fa-pencil"></i> Modifier
                <% end %>
                <%= link_to(admin_delete_actuality_path(actuality)) do %>
                <i class="fa fa-trash-o"></i> Supprimer
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/show_alert.html.erb
<h1>Gérer les alertes</h1>
<%= link_to(admin_create_user_path(),:class=>'button button-blue float-right') do %>
    <span>Créer une alerte</span> <i class="fa fa-user"></i>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Contenu</th>
            <th>Niveau</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
    <% @alerts.each do |alert| %>
        <tr>
            <td data-th="ID"><%= alert.id %></td>
            <td data-th="Nom"><%= alert.name %></td>
            <td data-th="Contenu"><%= alert.content %></td>
            <td data-th="Niveau"><%= alert.level %></td>
            <td data-th="Active"><%= alert.active %></td>
            <td data-th="Actions">
                <%= link_to(admin_edit_user_path(alert)) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
                <%= link_to(admin_delete_user_path(alert)) do %>
                <i class="fa fa-trash-o"></i></td>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/show_options.html.erb
<table class="table table-setting">
    <thead>
        <tr>
            <th>Options</th>
            <th>Valeur</th>
        </tr>
    </thead>
    <tbody>
    <% @options.each do |option| %>
        <tr>
            <td data-th="Options"><%= on_name_option_for_key(option.key) %></td>
            <td data-th="Valeur">
            <%= form_tag({:action => 'update_options'}, {:method => :post,:class =>'form-inline form-create-interview'}) do |f| %>
                    <%= hidden_field_tag :id , option.id %>
                    <%= hidden_field_tag :key , option.key %>
                    <%= hidden_field_tag :value , option.value %>
                    <button class="btn-options-switch <%= on_option_value(option.value) == true ? "on" : "" %>" type="submit">
                        <span class="track"></span>
                        <span class="ball green">|</span>
                        <span class="ball red"></span>
                    </button>
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/admin/show_users.html.erb
<h1>Gérer les comptes utilisateurs</h1>
<%= link_to(admin_create_user_path(),:class=>'button button-blue float-right') do %>
    <span>Créer un utilisateur</span> <i class="fa fa-user"></i>
<% end %>
<table class="table myTable">
    <thead>
        <tr>
            <th>ID</th>
            <th>Email</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Rôle</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
        <tr>
            <td data-th="ID"><%= user.id %></td>
            <td data-th="Email"><%= user.email %></td>
            <td data-th="Prénom"><%= user.name %></td>
            <td data-th="Nom"><%= user.lastname %></td>
            <td data-th="Rôle"><%= user.role %></td>
            <td data-th="Action">
                <%= link_to(admin_edit_user_path(user)) do %>
                <i class="fa fa-pencil"></i> Modifier
                <% end %>
                <%= link_to(admin_delete_user_path(user)) do %>
                <i class="fa fa-trash-o"></i> Supprimer
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>