config/routes.rb
Rails.application.routes.draw do



devise_for :users, :controllers => {:sessions => "sessions"},
path: '/',
:path_names => {
    :sign_in  => 'login',
    :sign_up  => 'sign_up',
    :sign_out => 'logout'
  }


  root 'pages#home'
  resources :actualities, only: [:index, :show]
  resources :tips, only: [:index, :show]
  resources :password_resets
    
  namespace :admin_v2 do
    resources :actualities, except: [:show]
    resources :users, except: [:show]
    resources :projects, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tips, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tipcategories, only: [:new ,:create ,:edit, :destroy ,:index]
    resources :alerts, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :interview, only: [:new ,:create ,:index]
    resources :applicants, only: [:index,:show]
    resources :admin, only: [:index,:new]
    resources :companies, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :jobs, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :admin, only: [:index]
 end

  resource :applicant, only: [:new, :create, :edit, :update, :show]
  resource :user, only: [:edit,:update]


  post 'admin_v2/applicants/index/user_vote' => 'admin#user_vote', :as => 'user_vote'
  post 'admin_v2/applicants/index/user_vote_cancel' => 'admin#user_vote_cancel', :as => 'user_vote_cancel'

  post 'admin/show_applicants/applicant_complete', :to => 'admin#applicant_complete', :as => 'applicant_complete'
  post 'admin/show_applicants/ok_for_interview', :to => 'admin#ok_for_interview', :as => 'ok_for_interview'
  post 'admin/show_applicants/is_refused', :to => 'admin#is_refused', :as => 'is_refused'
  post 'admin/show_applicants/is_accepted', :to => 'admin#is_accepted', :as => 'is_accepted'
  post 'admin/show_applicants/applicant_finish', :to => 'admin#applicant_finish', :as => 'applicant_finish'
  post 'admin/show_applicants/interview_result', :to => 'admin#interview_result', :as => 'interview_result'
  post 'admin/show_applicants/user_destroy', :to => 'admin#user_destroy', :as => 'user_destroy'
  get 'admin_v2/enable/:id' => 'admin_v2/jobs#enable', :as => 'admin_v2_enable_job'
  get 'admin_v2/disable/:id' => 'admin_v2/jobs#disable', :as => 'admin_v2_disable_job'

  get 'admin' => 'admin#index'
  get 'admin/sign_up' => 'admin#index'
  get 'admin/student_old/:id/graduate_student' => 'admin#graduate_student', :as => 'admin_graduate_student'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/show_applicants/send_remind', :to => 'admin#send_remind', :as => 'send_remind'



  get 'admin/show_options' => 'admin#show_options'
  get 'admin/show_options' => 'admin#show_options'
  post 'admin/update_options' => 'admin#update_options'

  get '/annuaire' => 'companies#annuary', :as => 'annuary'
  get '/entreprises/:page' => 'companies#companies', :as => "companies", defaults: { page: 1 }
  get '/entreprise/:id' => 'companies#company', :as => "company"
  get '/offres/:page' => 'jobs#jobs', :as => 'jobs', defaults: {page: 1}
  get '/offre/:id' => 'jobs#job', :as => 'job'

  get '/', :to => 'pages#home'
  get '/formation', :to => 'pages#formation'
  get '/projets', :to => 'pages#project'
  get '/equipe', :to => 'pages#team'
  get '/ucp', :to => 'pages#ucp'
  get '/informations', :to => 'pages#map'
  post '/informations/sendmail', :to => 'pages#sendmail'
  get '/postuler', :to => 'applicants#new'
  post '/postuler/login', :to => 'applicant#applicant_login', :as => 'applicant_login'
  get '/postuler/:assurance', :to => 'applicant#applicant_create_apply', :as => 'applicant_create_apply'
  post '/postuler/new', :to => 'applicant#create_apply', :as => 'create_apply'
  patch '/postuler/:assurance', :to => 'applicant#update_apply', :as => 'update_apply'
  get '/mentions', :to => 'pages#mentions'
  get '/live', :to => 'pages#live'

  get '/studentsbook', :to => 'student#show', :as => 'students_list'
  get '/studentsbook/:graduation_years' , :to => 'student#show', :as => 'students_list_by_year'
  post 'studentsbook/', :to => 'student#show'
  post 'studentsbook/:graduation_years', :to => 'student#show'
  get '/studentprofil/:user_id', :to => 'student#profil', :as => 'student_profil'
  post '/studentprofil/sendmail', :to => 'student#sendmail'
  get '/studentprofil/edit/:user_id', :to => 'student#edit', :as => 'student_profil_edit'
  post '/studentprofil/update_user/:user_id', :to => 'student#update_user'
  resources :tips, only: [:show,:index] do
    resources :errors_tips
  end
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id              :integer          not null, primary key
#  job_name        :string(255)
#  job_number      :string(255)
#  job_description :text(4294967295)
#  start_at        :string(255)
#  duration        :string(255)
#  profil          :text(4294967295)
#  contact         :string(255)
#  location        :string(255)
#  skills          :text(4294967295)
#  status          :integer
#  founded_at      :date
#  posted_by       :integer
#  created_at      :datetime
#  updated_at      :datetime
#  company_id      :integer
#

class Job < ActiveRecord::Base
  belongs_to :company
  accepts_nested_attributes_for :company

	validates :contact, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
end


app/controllers/admin_v2/jobs_controller.rb
class AdminV2::JobsController < AdminV2Controller

	def index
		@title_admin = "Offre d'emploi"
		@jobs = Job.all
	end

	def new
		@title_admin = "Offre d'emploi"
		@job = Job.new
		@job.status = 1
		@companies = Company.all
	end

	def create
		# == Admin restriction == #
    	admin_restriction_area
		@job = Job.new(params[:job].permit(:job_name,:job_number,:job_description,:start_at,:duration,:profil,:contact,:location,:skills,:status))
		@job.company_id = params[:company_id]
		if @job.save
			flash["sucess"] = "Offre d'emploi créée"
			redirect_to admin_v2_jobs_path()
		else
			flash["fail"] = "Erreur création de l'offre"
			redirect_to new_admin_v2_job_path()
		end
	end

	def edit
		@title_admin = "Offre d'emploi"
		@job = Job.find(params[:id]) 
		@companies = Company.all
	end

	def update
		@title_admin = "Offre d'emploi"
		@job = Job.find(params[:id])
		@job.company_id = (params[:company_id] === "0") ? nil : params[:company_id]

		if @job.update_attributes(params[:job].permit(:job_name, :job_number, :job_description, :start_at, :duration, :profil, :contact, :location, :skills, :status))
			flash["sucess"] = "Offre d'emploi mise à jour"
			redirect_to admin_v2_jobs_path()
		else
			redirect_to edit_admin_v2_job_path(job)
		end
	end

	def destroy
		@job = Job.find(params[:id])
		
		if @job.destroy
			flash["sucess"] = "Offre d'emploi supprimée"
			redirect_to admin_v2_jobs_path()
		else
			flash[:error] = "Erreur de suppression d'offre d'emploi"
			redirect_to admin_v2_jobs_path()
		end
	end

	def enable
		@job = Job.find(params[:id])
		@job.status = 1
			
		if @job.save
			flash["sucess"] = "Offre d'emploi activée"
			redirect_to admin_v2_jobs_path()
		else
			flash["fail"] = "Erreur"
			redirect_to admin_v2_jobs_path()
		end
	end

	def disable
		@job = Job.find(params[:id])
		@job.status = 0
			
		if @job.save
			flash["sucess"] = "Offre d'emploi désactivée"
			redirect_to admin_v2_jobs_path()
		else
			flash["fail"] = "Erreur"
			redirect_to admin_v2_jobs_path()
		end
	end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :is_student_or_admin
  
	def job
		@job = Job.find(params["id"])
	end

	def jobs
		@pageCurrent = params["page"].to_i
		max = Job.where(status: 1).count
		limit = 5
		@pageMax = (max.to_f / limit.to_f).ceil

		@jobs = Job.where(status: 1).limit(limit).offset((@pageCurrent - 1) * limit).order(id: :desc)

		if @jobs.count === 0 and @pageCurrent > 1
			redirect_to jobs_path(1)
		end
	end

end


app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/create_job.html.erb
<h2>Ajouter une offre</h2>
<%= form_for(@job, url:  admin_create_job_path, html: {class: "form" }) do |f| %>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :job_name, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :job_number, autofocus: true , :class => 'input' ,:placeholder=>"Numéro l'offre" %>
 </div>
</div>

</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_area :job_description, :class => "tinymce", :rows => 40, :cols => 120, :placeholder=>"Description" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :start_at, autofocus: true , :class => 'input' ,:placeholder=>"Début de l'offre" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :duration,:class => 'input' ,:placeholder=>"Durée de l'offre"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :profil,:class => 'input' ,:placeholder=>"Profil recommandé"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :skills,:class => 'input' ,:placeholder=>"Compétences"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :contact ,:class => 'input' ,:placeholder=>"Contact"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :location,:class => 'input' ,:placeholder=>"Lieu"  %>
 </div>
</div>

<div class="form-group">
  <select class="form-control" name="company_id">
  <% @companies.each do |company| %> 
    <option value="<%= company.id  %>"><%= company.name %></option>
  <% end %>
  </select>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.submit "Créer une offre", :class => 'input-btn' %>
 </div>
</div>
<% end %>

app/views/jobs/edit_job.html.erb
<h2>Modifierr une offre</h2>
<%= form_for(@job, url:  admin_edit_job_path, html: {class: "form" }) do |f| %>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :job_name, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :job_number, autofocus: true , :class => 'input' ,:placeholder=>"Numéro l'offre" %>
 </div>
</div>

</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_area :job_description, :class => "tinymce", :rows => 40, :cols => 120, :placeholder=>"Description" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :start_at, autofocus: true , :class => 'input' ,:placeholder=>"Début de l'offre" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :duration,:class => 'input' ,:placeholder=>"Durée de l'offre"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :profil,:class => 'input' ,:placeholder=>"Profil recommandé"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :skills,:class => 'input' ,:placeholder=>"Compétences"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :contact ,:class => 'input' ,:placeholder=>"Contact"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :location,:class => 'input' ,:placeholder=>"Lieu"  %>
 </div>
</div>

<div class="form-group">
  <select class="form-control" name="company_id">
  <% @companies.each do |company| %>
    <option value="<%=company.id %>"
	<%= 
        @selected = ""
	if @job.company.id == company.id
  	  @selected = "selected"
	end
	@selected %>
    ><%= company.name %></option>
  <% end %>
  </select>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.submit "Créer une offre", :class => 'input-btn' %>
 </div>
</div>
<% end %>

app/views/jobs/job.html.erb
<section class="banner banner-red">
	<div class="container">
		<p>Offre d'emploi</p>
	</div>
</section>

<div class="bg-white new">
	<div class="container">
		<div class="row">

			<article class="col-md-12">
				<%= link_to(jobs_path,:class=>'more-article') do %>
					<i class="fa fa-chevron-left"></i><span>Revenir à la liste des offres</span>
				<% end %>

				<h1 class="new-title text-center"><%= @job.job_name %></h1>

				<div class="row date-job">
					<div class="col-md-4 text-center"><strong>Date d'apparition :</strong> <%= @job.created_at.strftime("%m/%d/%Y") %></div>
					<% if @job.start_at %>
					<div class="col-md-4 text-center"><strong>Date de début :</strong> <%= @job.start_at %></div>
					<% end %>
					<% if @job.duration %>
					<div class="col-md-4 text-center"><strong>Durée du contrat :</strong> <%= @job.duration %></div>
					<% end %>
				</div>

				<div class="container formation">
					<div class="col-md-offset-2 col-md-8">

						<blockquote>
							<% if @job.company %>
							<h2><%= link_to @job.company.name, company_path(@job.company.id) %></h2>
							<strong>Contact :</strong> <%= @job.company.phone_number %> - <%= @job.contact %>
							<% else %>
							<strong>Contact : </strong> <%= @job.contact %>
							<% end %>
						</blockquote>

					</div>
				</div>

				<% if @job.job_number %>
				<div class="col-md-12">
					<h2>Description de l'offre N° <%= @job.job_number %></h2>			
					<%= raw @job.job_description %>
				</div>
				<% end %>

				<% if @job.profil %>
				<div class="col-md-4 text-center">
					<h2>Profil recommandé</h2>	
					<%= @job.profil %>
				</div>
				<% end %>

				<% if @job.skills %>
				<div class="col-md-4 text-center">
					<h2>Compétences requises</h2>
					<%= @job.skills %>
				</div>
				<% end %>

				<% if @job.location %>
				<div class="col-md-4 text-center">
					<h2>Lieu du contrat</h2>
					<%= @job.location %>
				</div>
				<% end %>

			</article>

		</div>
	</div>
</div>

app/views/jobs/jobs.html.erb
<section class="banner banner-red">
	<div class="container">
		<p>Annuaire d'entreprises</p>
	</div>
</section>

<!-- LISTE OFFRES -->
<div class="gray-bg wrapper">
	<div class="container">
		<div class="row">

			<%= link_to(annuary_path,:class=>'more-article') do %>
				<i class="fa fa-chevron-left"></i><span>Revenir à l'accueil annuaire</span>
			<% end %>

			<section class="col-md-10 col-md-offset-1 home-news">
				<h1>Offres d'emploi</h1>

				<div class="row">
					<% @jobs.each_with_index do |job, i| %>

						<% if i % 3 === 2 %>
							<article class="col-md-12">
							<% word = 40 %>
						<% else %>
							<article class="col-md-6">
							<% word = 15 %>
						<% end %>

							<div class="article-new">
								<h3><%= job.job_name %></h3>

								<div class="article-excerpt">
									<%= HTML_Truncator.truncate((job.job_description), word).html_safe %>
								</div>

								<%= link_to(job,:class=>'button') do %>
									Voir <i class="fa fa-chevron-right"></i>
								<% end %>
							</div>

						</article>
					<% end %>
				</div>

			</section>
		</div>

		<ul class="pagination pull-right">
			<% if @pageCurrent > 1 %>
				<li>
					<%= link_to '<', jobs_path(@pageCurrent - 1) %>
				</li>
			<% end %>

			<% 1.upto(@pageMax) do |i| %>
				<li <% if i == @pageCurrent %>class="active"<% end %>>
					<%= link_to(i, jobs_path(i)) %>
				</li>
			<% end %>

			<% if @pageCurrent < @pageMax %>
				<li>
					<%= link_to '>', jobs_path(@pageCurrent + 1) %>
				</li>
			<% end %>
		</ul>

	</div>
</div>

app/views/jobs/show_jobs.html.erb
<h1>Liste des offres d'emplois</h1>
<%= link_to(admin_create_job_path(),:class=>'button button-blue float-right') do %>
    <span>Créer une offre d'emploi</span> <i class="fa fa-newspaper-o"></i>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Entreprise</th>
            <!-------- <th>Statut</th> ----->
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @jobs.each do |job| %>
        <tr>
            <td data-th="ID" ><%= job.id %></td>
            <td data-th="Nom" ><%= job.job_name %></td>
            <td data-th="Entreprise" ><%= job.company.name %></td>
           <!-----  <td data-th="Statut" ><%= job.status %></td> ------->
            <td data-th="Action" >
                <%= link_to(admin_edit_job_path(job)) do %>
                <i class="fa fa-pencil"></i> Modifier
                <% end %>
                <%= link_to(admin_delete_job_path(job)) do %>
                <i class="fa fa-trash-o"></i> Supprimer
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>