config/routes.rb
Rails.application.routes.draw do



devise_for :users, :controllers => {:sessions => "sessions"},
path: '/',
:path_names => {
    :sign_in  => 'login',
    :sign_up  => 'sign_up',
    :sign_out => 'logout'
  }


  root 'pages#home'
  resources :actualities, only: [:index, :show]
  resources :tips, only: [:index, :show]
  resources :password_resets
    
  namespace :admin_v2 do
    resources :actualities, except: [:show]
    resources :users, except: [:show]
    resources :projects, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tips, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :tipcategories, only: [:new ,:create ,:edit, :destroy ,:index]
    resources :alerts, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :interview, only: [:new ,:create ,:index]
    resources :applicants, only: [:index,:show]
    resources :admin, only: [:index,:new]
    resources :companies, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :jobs, only: [:new ,:create ,:edit ,:update, :destroy ,:index]
    resources :admin, only: [:index]
 end

  resource :applicant, only: [:new, :create, :edit, :update, :show]
  resource :user, only: [:edit,:update]


  post 'admin_v2/applicants/index/user_vote' => 'admin#user_vote', :as => 'user_vote'
  post 'admin_v2/applicants/index/user_vote_cancel' => 'admin#user_vote_cancel', :as => 'user_vote_cancel'

  post 'admin/show_applicants/applicant_complete', :to => 'admin#applicant_complete', :as => 'applicant_complete'
  post 'admin/show_applicants/ok_for_interview', :to => 'admin#ok_for_interview', :as => 'ok_for_interview'
  post 'admin/show_applicants/is_refused', :to => 'admin#is_refused', :as => 'is_refused'
  post 'admin/show_applicants/is_accepted', :to => 'admin#is_accepted', :as => 'is_accepted'
  post 'admin/show_applicants/applicant_finish', :to => 'admin#applicant_finish', :as => 'applicant_finish'
  post 'admin/show_applicants/interview_result', :to => 'admin#interview_result', :as => 'interview_result'
  post 'admin/show_applicants/user_destroy', :to => 'admin#user_destroy', :as => 'user_destroy'
  get 'admin_v2/enable/:id' => 'admin_v2/jobs#enable', :as => 'admin_v2_enable_job'
  get 'admin_v2/disable/:id' => 'admin_v2/jobs#disable', :as => 'admin_v2_disable_job'

  get 'admin' => 'admin#index'
  get 'admin/sign_up' => 'admin#index'
  get 'admin/student_old/:id/graduate_student' => 'admin#graduate_student', :as => 'admin_graduate_student'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/tinymce_assets' => 'admin#create_tinymce_assets'
  post 'admin/show_applicants/send_remind', :to => 'admin#send_remind', :as => 'send_remind'



  get 'admin/show_options' => 'admin#show_options'
  get 'admin/show_options' => 'admin#show_options'
  post 'admin/update_options' => 'admin#update_options'

  get '/annuaire' => 'companies#annuary', :as => 'annuary'
  get '/entreprises/:page' => 'companies#companies', :as => "companies", defaults: { page: 1 }
  get '/entreprise/:id' => 'companies#company', :as => "company"
  get '/offres/:page' => 'jobs#jobs', :as => 'jobs', defaults: {page: 1}
  get '/offre/:id' => 'jobs#job', :as => 'job'

  get '/', :to => 'pages#home'
  get '/formation', :to => 'pages#formation'
  get '/projets', :to => 'pages#project'
  get '/equipe', :to => 'pages#team'
  get '/ucp', :to => 'pages#ucp'
  get '/informations', :to => 'pages#map'
  post '/informations/sendmail', :to => 'pages#sendmail'
  get '/postuler', :to => 'applicants#new'
  post '/postuler/login', :to => 'applicant#applicant_login', :as => 'applicant_login'
  get '/postuler/:assurance', :to => 'applicant#applicant_create_apply', :as => 'applicant_create_apply'
  post '/postuler/new', :to => 'applicant#create_apply', :as => 'create_apply'
  patch '/postuler/:assurance', :to => 'applicant#update_apply', :as => 'update_apply'
  get '/mentions', :to => 'pages#mentions'
  get '/live', :to => 'pages#live'

  get '/studentsbook', :to => 'student#show', :as => 'students_list'
  get '/studentsbook/:graduation_years' , :to => 'student#show', :as => 'students_list_by_year'
  post 'studentsbook/', :to => 'student#show'
  post 'studentsbook/:graduation_years', :to => 'student#show'
  get '/studentprofil/:user_id', :to => 'student#profil', :as => 'student_profil'
  post '/studentprofil/sendmail', :to => 'student#sendmail'
  get '/studentprofil/edit/:user_id', :to => 'student#edit', :as => 'student_profil_edit'
  post '/studentprofil/update_user/:user_id', :to => 'student#update_user'
  resources :tips, only: [:show,:index] do
    resources :errors_tips
  end
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  description  :text(4294967295)
#  address      :string(255)
#  zip_code     :string(255)
#  city         :string(255)
#  phone_number :string(255)
#  website      :string(255)
#  twitter      :string(255)
#  linkedin     :string(255)
#  logo_url     :string(255)
#  founded_at   :date
#  posted_by    :integer
#  created_at   :datetime
#  updated_at   :datetime
#

class Company < ActiveRecord::Base
  has_many :jobs, :dependent => :nullify
  has_many :users
end


app/controllers/admin_v2/companies_controller.rb
class AdminV2::CompaniesController < AdminV2Controller

	def index
		@title_admin = "Entreprises"
		@companies = Company.all
	end

	def new
		@title_admin = "Entreprise"
		@company = Company.new
	end

	def create
		@title_admin = "Entreprise"
		@company = Company.new(params[:company].permit(:name, :description, :address, :zip_code, :city, :phone_number, :website, :twitter, :linkedin))
		
		if @company.save
			flash["sucess"] = "Entreprise créée"
			redirect_to admin_v2_companies_path()
		else
			flash["fail"] = "Erreur de création d'entreprise"
			redirect_to new_admin_v2_company_path()
		end
	end

	def edit
		@title_admin = "Entreprise"    
		@company = Company.find(params[:id])
	end

	def update
		@title_admin = "Entreprise"
		@company = Company.find(params[:id])

		if @company.update_attributes(params[:company].permit(:name, :description, :address, :zip_code, :city, :phone_number, :website, :twitter, :linkedin))
			flash["sucess"] = "Entreprise mise à jour"
			redirect_to admin_v2_companies_path
		else
			redirect_to edit_admin_v2_company_path(company)
		end
	end

	def destroy
		@company = Company.find(params[:id])

		if @company.destroy
			flash["sucess"] = "Entreprise supprimée"
			redirect_to admin_v2_companies_path()
		else
			flash[:error] = "Erreur de suppression d'entreprise"
			redirect_to admin_v2_companies_path()
		end    
	end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_action :is_student_or_admin

	def annuary
	end

	def company
		@company = Company.find(params["id"])
	end

	def companies
		@pageCurrent = params["page"].to_i
		max = Company.count
		limit = 5
		@pageMax = (max.to_f / limit.to_f).ceil

		@companies = Company.limit(limit).offset((@pageCurrent - 1) * limit).order(name: :asc)

		if @companies.count === 0 and @pageCurrent > 1
			redirect_to companies_path(1)
		end
	end

end


app/views/companies/annuary.html.erb
<section class="banner banner-red">
	<div class="container">
		<p>Annuaire d'entreprises</p>
	</div>
</section>

<!-- ANNUAIRE ENTREPRISES ET OFFRES -->
<div class="gray-bg wrapper">
	<div class="container">
		<div class="row">

			<section class="col-md-10 col-md-offset-1 home-news">
				<h3 class="content-title">Accéder aux entreprises ou aux offres d'emploi</h3><br />

				<div class="row">
					<article class="col-md-6">
						<div class="article-new">

							<h3>Entreprises</h3>
							<p>
								Vous pouvez accéder à toutes les entreprises qui collaborent avec l'université de Cergy-Pontoise et y découvrir de nombreuses informations(Coordonnées, sites, descriptions, etc).
							</p>
   
							<%= link_to(companies_path(),:class=>'button') do %>
								<span>Voir les entreprises</span> <i class="fa fa-chevron-right"></i>
							<% end %>
						</div>
					</article>

					<article class="col-md-6">
						<div class="article-new">

							<h3>Les offres d'emploi</h3>
							<p>
								Pour faciliter vos recherches, vous pouvez accéder à de nombreuses offres d'emploi pour mener à bien votre licence professionelle. A vous de contacter directement celles qui vous intéressent !
							</p>

							<%= link_to(jobs_path(),:class=>'button') do %>
								<span>Voir les offres</span> <i class="fa fa-chevron-right"></i>
							<% end %>
						</div>
					</article>
				</div>

			</section>

		</div>
	</div>
</div>

app/views/companies/companies.html.erb
<section class="banner banner-red">
	<div class="container">
		<p>Annuaire d'entreprises</p>
	</div>
</section>

<!-- LISTE ENTREPRISES -->
<div class="gray-bg wrapper">
	<div class="container">
		<div class="row">

			<%= link_to(annuary_path,:class=>'more-article') do %>
				<i class="fa fa-chevron-left"></i><span>Revenir à l'accueil annuaire</span>
			<% end %>

			<section class="col-md-10 col-md-offset-1 home-news">
				<h1>Entreprises</h1>
         
				<div class="row">
					<% @companies.each_with_index do |company, i| %>

						<% if i%3===2  %>
							<article class="col-md-12">
							<% word = 40 %>
						<% else %>
							<article class="col-md-6">
							<% word = 20 %>
						<% end %>

							<div class="article-new">
								<h3><%= company.name %></h3>
	
								<div class="article-excerpt">
									<%= HTML_Truncator.truncate((company.description), word).html_safe %>
								</div>
					
								<%= link_to(company,:class=>'button') do %>
									<span>Voir</span> <i class="fa fa-chevron-right"></i>
								<% end %>
							</div>
						</article>
					<% end %>
				</div>
			</section>

		</div>

		<ul class="pagination pull-right">
			<% if @pageCurrent > 1 %>
				<li>
					<%= link_to '<', companies_path(@pageCurrent - 1) %>
				</li>
			<% end %>

			<% 1.upto(@pageMax) do |i| %>
				<li <% if i == @pageCurrent %>class="active"<% end %>>
					<%= link_to(i, companies_path(i)) %>
				</li>
			<% end %>

			<% if @pageCurrent < @pageMax %>
				<li>
					<%= link_to '>', companies_path(@pageCurrent + 1) %>
				</li>
			<% end %>
		</ul>

	</div>
</div>

app/views/companies/company.html.erb
<section class="banner banner-red">
	<div class="container">
		<p>Annuaire d'entreprises</p>
	</div>
</section>

<!-- ENTREPRISE -->
<div class="gray-bg wrapper">
	<div class="container">
		<div class="row">

			<%= link_to(companies_path,:class=>'more-article') do %>
				<i class="fa fa-chevron-left"></i><span>Revenir à la liste des entreprises</span>
			<% end %> 

			<section id="company_t" class="col-md-10 col-md-offset-1 home-news">

				<article class="no-height"  class="col-md-12">
					<div id="comp_content" class="article-new">
						<h1 id="comp_title" class="text-center"><%= @company.name %></h1>
					</div>
				</article>
				
				<% if @company.description %>
				<article class="no-height" class="col-md-12">
					<div class="article-new">
						<h2 class="text-center">Description</h2>
						<p class="comp_desc"> <%= raw  @company.description %> </p>
					</div>
				</article>
				<% end %>

				<% if @company.address or @company.zip_code or @company.city %>
				<article class="col-md-5">
					<div class="article-new">
						<h2 class="text-center"> Adresse </h2>
						<% if @company.address %>
						<p><%= @company.address %></p>
						<% end %>
						<% if @company.zip_code or @company.city %>
						<p><%= @company.zip_code %> <%= @company.city %></p>
						<% end %>
					</div>
				</article>
				<% end %>

				<% if @company.website or @company.phone_number or @company.twitter or @company.linkedin %>
				<article class="col-md-7">
					<div class="article-new">
						<h2 class="text-center"> Contact </h2>
			
						<div class="row">
							
							<% if @company.website or @company.phone_number %>
							<div class="col-md-6 text-center">	
								<p><a href="<%= @company.website %>"><%= @company.website %></a></p>
								<p><%= @company.phone_number %></p>
							</div>
							<% end %>

							<div class="col-md-6 text-center">
								<% if @company.twitter.present? or @company.linkedin.present? %>
									<p class="social_section">
										<% if @company.linkedin.present? %>
											<p><a target="_blank" href=<%= @company.linkedin%>><i class="fa fa-linkedin"></i></a></p>
										<% end %>

										<% if @company.twitter.present? %>
											<p><a target="_blank" href=<%= @company.twitter%>><i class="fa fa-twitter"></i></a></p>
										<% end %>
									</p>
								<% end %>
							</div>

						</div>

					</div>
				</article>
				<% end %>

				<% if @company.jobs.empty? === false  %>
					<article class="col-md-12 no-height">
						<div class="article-new">
							<h2 class="text-center">Offres d'emploi disponibles</h2>

							<table class="og-grid table-offers">
								<thead>
									<tr>
										<td>Poste</td>
										<td>Ville</td>
										<td>Lien</td>
									</tr>
								</thead>
	
								<% @company.jobs.each do |job| %>
									<tr>
										<td><%= job.job_name %></td>
										<td><%= job.location %></td>
										<td>
											<%= link_to job_path(job.id) , html_options = {"class" =>""} do %> 
												<span class="fa fa-eye"></span>
											<% end %>
										</td>
									</tr>
								<% end %>  
							</table>	

						</div>
					</article>
				<% end %>

			</section>
		</div>
	</div>
</div>

app/views/companies/create_company.html.erb
<h2>Ajouter une entreprise</h2>
<%= form_for(@company, url:  admin_create_company_path, html: {class: "form" }) do |f| %>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :name, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :address, autofocus: true , :class => 'input' ,:placeholder=>"Adresse" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :zip_code, autofocus: true , :class => 'input' ,:placeholder=>"Code Postal" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :city, autofocus: true , :class => 'input' ,:placeholder=>"Ville" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :phone_number, autofocus: true , :class => 'input' ,:placeholder=>"Numéro de téléphone" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :website ,:class => 'input' ,:placeholder=>"Lien de l'entreprise"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :twitter ,:class => 'input' ,:placeholder=>"Lien de Twitter"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :linkedin ,:class => 'input' ,:placeholder=>"Lien de Linkedin"  %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.submit "Créer une entreprise", :class => 'input-btn' %>
 </div>
</div>
<% end %>

app/views/companies/edit_company.html.erb
<h2>Ajouter une entreprise</h2>
<%= form_for(:company, url:  admin_edit_company_path, html: {class: "form" }) do |f| %>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :name, autofocus: true , :class => 'input' ,:placeholder=>"Nom" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :address, autofocus: true , :class => 'input' ,:placeholder=>"Adresse" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :zip_code, autofocus: true , :class => 'input' ,:placeholder=>"Code Postal" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :city, autofocus: true , :class => 'input' ,:placeholder=>"Ville" %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_area :description, :class => "tinymce", :rows => 40, :cols => 120 %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :phone_number, autofocus: true , :class => 'input' ,:placeholder=>"Numéro de téléphone" %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :website ,:class => 'input' ,:placeholder=>"Lien de l'entreprise"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :twitter ,:class => 'input' ,:placeholder=>"Lien de Twitter"  %>
 </div>
</div>
<div class="form-group">
 <div class="col-sm-10">
   <%= f.text_field :linkedin ,:class => 'input' ,:placeholder=>"Lien de Linkedin"  %>
 </div>
</div>

<div class="form-group">
 <div class="col-sm-10">
   <%= f.submit "Créer une entreprise", :class => 'input-btn' %>
 </div>
</div>
<% end %>

app/views/companies/show_companies.html.erb
<h1>Liste des entreprises</h1>
<%= link_to(admin_create_company_path(),:class=>'button button-blue float-right') do %>
    <span>Créer une entreprisee</span> <i class="fa fa-newspaper-o"></i>
<% end %>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nom</th>
            <th>Site internet</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    <% @companies.each do |company| %>
        <tr>
            <td data-th="ID" ><%= company.id %></td>
            <td data-th="Titre" ><%= company.name %></td>
	    <td data-th="E-mail" ><%= company.website	 %></td>"
            <td data-th="Action" >
                <%= link_to(admin_edit_company_path(company)) do %>
                <i class="fa fa-pencil"></i> Modifier
                <% end %>
                <%= link_to(admin_delete_company_path(company)) do %>
                <i class="fa fa-trash-o"></i> Supprimer
                <% end %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>